Update design of template + new SDK version
whopio/next-template pull request #5
Opened 2023-03-15 01:56 UTC by jacc

This PR includes the following changes
- Bump SDK version to 0.0.4, the latest available
- Redesign the template to use Vercel's newest Next.js 13 design

2023-03-15 02:21 UTC, baked-dev requested changes

2023-03-15 02:21 UTC, baked-dev commented on app/app/ssg/product-gated/page.tsx
> +        </Head>
the next.js app directory uses a special metadata export for setting these tags.
see: https://beta.nextjs.org/docs/api-reference/metadata

2023-03-15 02:21 UTC, baked-dev commented on app/app/ssg/product-gated/page.tsx
> +"use client";
does this not work as a server component?

2023-03-15 02:21 UTC, baked-dev commented on app/app/ssr/product-gated/PurchaseLink.tsx
> +const inter = Inter({ subsets: ["latin"] });
this appears to be unused

2023-03-15 02:26 UTC, baked-dev commented on app/app/ssg/product-gated/page.tsx
> +        </Head>
you might have to update the version of next we use to enable this feature, its been introduced in 13.2

2023-03-15 16:05 UTC, stevo2105 commented
#### 📝 Changed routes:


| [**/**](https://next-template-3kegpiw5k-whop.vercel.app/) | [**/ssg/product-gated**](https://next-template-3kegpiw5k-whop.vercel.app/ssg/product-gated) |
|:-:|:-:|
|<a href="https://next-template-3kegpiw5k-whop.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/6Dt_Kx1Vk2oFifrCh8x29gImRPEj2-C63pZuOK6gpMzJl04aPJKA_aOxtD33Mr-jZDYHCz9GlihWHEjjorUFrA.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xUYbggWUc45AMvMRrYv_JaXK69smyS8-hT9oDubeLOP67Eb_paaJgH4nIR5_GPxDVACgvvxG8rlIDihYyFSHIg.png">(view full size)</a> |<a href="https://next-template-3kegpiw5k-whop.vercel.app/ssg/product-gated"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/duqZgnKJ5JBQXoagOeTMFyFvzdnNPOnHBgwmRdoNAlDvWUnHF0VmWli1w28z7Ac00FBgGsJ0_FJQglgcRX3fxA.png&w=600" alt="Screenshot of /ssg/product-gated" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/R1WMsUHuZ6OrrnCAt3ajRN1KIa3XyIZZysczWKuvA-LcFJCh-KXgnbj5b834eCdC0h8pewQVUKtThIiQBvKt4w.png">(view full size)</a> |



| [**/ssr**](https://next-template-3kegpiw5k-whop.vercel.app/ssr) | [**/ssr/logged-in**](https://next-template-3kegpiw5k-whop.vercel.app/ssr/logged-in) |
|:-:|:-:|
|<a href="https://next-template-3kegpiw5k-whop.vercel.app/ssr"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/BTsY1_pHW9O00vFeBIHV2KY2iVE58_-2T3lPF2iHZ3l5lSPqhmNiyUh-6EzeZKqBShDfqmQv1NwmsZi_ssiltw.png&w=600" alt="Screenshot of /ssr" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/6cVFsMjgjMMhU6OS5GHGvZebrxoT8DePdmCP5f2DOchGBPAM3prYtSyYEOiFuLYLyBF8IJ-ha9SyRVA4bxgsDg.png">(view full size)</a> |<a href="https://next-template-3kegpiw5k-whop.vercel.app/ssr/logged-in"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/DWK7KawlXaHn8XAo2por_Mc9llqrBSTSMKNwrTPmWneQGLiziq3mOPg7g0n4IwNFNNM0oAutGB-G3JgPlLQyMg.png&w=600" alt="Screenshot of /ssr/logged-in" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/D1Lgm89MCpFTm4ej2zlfq7gAkDaLur3hsj3nO5zKIln5O80pLCVLgjZgsAKK4ICtD52Mfz70OmLzelvVKkykNw.png">(view full size)</a> |



| [**/ssr/product-gated**](https://next-template-3kegpiw5k-whop.vercel.app/ssr/product-gated) |
|:-:|
|<a href="https://next-template-3kegpiw5k-whop.vercel.app/ssr/product-gated"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/KS-NlFaGAX7ucpzfAIREFuD6ebNZhRmdioaa9IDBYaavsMh_CgyM5FYyKopSNVzVl0Z4zvOKr0aixY6EpU7EZw.png&w=600" alt="Screenshot of /ssr/product-gated" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/QsxEhsagK4PKJqJ8P8gEcvcel5ZGTp44NwKse80YSQdvEFAH1-3VZrCadOsr-LI9hdCtGoPqSi2Sf4YLy-iDfA.png">(view full size)</a> |







Commit f743d1305768e0f79db253914356ae4e5aa377c1 (https://next-template-3kegpiw5k-whop.vercel.app).

2023-03-15 16:06 UTC, jacc commented on app/app/ssg/product-gated/page.tsx
> +"use client";
it didn't before, but now removing it it does 🥴

2023-03-15 16:32 UTC, baked-dev requested changes

2023-03-15 16:32 UTC, baked-dev commented on app/app/ssr/product-gated/layout.tsx
> +        </Head>
please move this to metadata (or a head.tsx file if you dont want to update the next version yet)

2023-03-15 16:32 UTC, baked-dev commented on app/app/ssr/product-gated/page.tsx
>          </Head>
this is redundant as its already been set in the layout.tsx in the same segment

2023-03-15 16:33 UTC, baked-dev commented on app/app/ssr/product-gated/layout.tsx
> +        </Head>
just saw that its been updated to 12.2.4 so it should go into metadata

2023-03-16 16:14 UTC, baked-dev approved these changes

2023-03-16 19:15 UTC, baked-dev approved these changes

2023-03-16 19:16 UTC, merged